### ISSUE TITLE
Discord or Telegram?

### ISSUE THREAD

**Issue by 3devilscapital** [HuckleberryDex/huckleberry-interface#2]
Hi @molin0000 @JasonHJ @Gabriella1004 @neo75005 @morpheus-blockchain !
I just found your project and I would like to discuss with the team.

Do you have a Discord or a Telegram group, please?

Thank you!

Three Devils Capital

**Comment by lolieatapple** [comment]
Hi, telegram is: https://t.me/HuckleberryDex
